[package]
name = "serde-json-exercise"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
thiserror = "2.0.12"
itoa = "1.0.15"

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
